In [1]:
# import libraries

# Data Manipulation libraries
import pandas as pd
import numpy as np

# Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Data Preprocessing Libraries
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

# Machine Learning Libraries
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.svm import SVR

# Evaluation Metrics Libraries
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

# save model
import joblib

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# import data
df = pd.read_csv('Food_Delivery_Times.csv')
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [3]:
# information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [4]:
# statistic description
df.describe()

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,1000.000000,1000.000000,1000.000000,970.000000,1000.000000
mean,500.500000,10.059970,16.982000,4.579381,56.732000
std,288.819436,5.696656,7.204553,2.914394,22.070915
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,250.750000,5.105000,11.000000,2.000000,41.000000
50%,500.500000,10.190000,17.000000,5.000000,55.500000
75%,750.250000,15.017500,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,153.000000

In [5]:
# numerical column
num_col = df.select_dtypes(include = ['int64', 'float64']).columns
print(num_col)

print('-'*75)

# categorical column
cat_col = df.select_dtypes(include = ['object']).columns
print(cat_col)

Index(['Order_ID', 'Distance_km', 'Preparation_Time_min',
       'Courier_Experience_yrs', 'Delivery_Time_min'],
      dtype='object')
---------------------------------------------------------------------------
Index(['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type'], dtype='object')

In [6]:
# check the missing values
print(df.isnull().sum())

print('-'*35)

# check duplicated values
print(df.duplicated().sum())

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64
-----------------------------------
0

In [7]:
# lenght of numerical and categorical columns
print(f'number of numerical columns: {len(num_col)}')
print(f'number of categorical columns: {len(cat_col)}')

number of numerical columns: 5
number of categorical columns: 4

# **Train Test Split**

In [8]:
# define featrures and target variable
X = df.drop('Delivery_Time_min', axis=1)
y = df['Delivery_Time_min']

# train test split 
from sklearn.model_selection import train_test_split

# split the data into training and testing sets with 80% for training and 20% for testing, and set random_state to 42 for reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, 
    test_size=0.20, 
    random_state=42
)

In [9]:
# information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

In [10]:
# numerical col
numeric_col = ['Distance_km', 'Preparation_Time_min', 'Courier_Experience_yrs']

# ordinal column
ordinal_col = ['Traffic_Level']

# nominal column
nominal_col = ['Weather', 'Time_of_Day', 'Vehicle_Type']

In [11]:
# set ordinal category
ordinal_category = ['Low', 'Medium', 'High']

# **Cleaning and Preprocessing**

In [12]:
# import libaray for data preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [13]:
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

ordinal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(categories=[ordinal_category]))
])

nominal_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [14]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_col),
        ('ord', ordinal_transformer, ordinal_col),
        ('nom', nominal_transformer, nominal_col)
])

# **Build Machine Learning Model**

**1. Linear Regression**

In [15]:
# train model with linear regression
from sklearn.linear_model import LinearRegression

# create pipeline for linear regression
pipeline_linreg = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

# train the model with linear regression pipeline
pipeline_linreg.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('regressor', LinearRegression())])

In [16]:
# predict the test set data
y_pred_linreg = pipeline_linreg.predict(X_test)

In [17]:
# evaluate the model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred_linreg)
mse = mean_squared_error(y_test, y_pred_linreg)
mape = mean_absolute_percentage_error(y_test, y_pred_linreg)*100
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_linreg)

print(f'Mean Absolute Error: {mae:.2f}') 
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Percetage Error: {mape:.2f}%')
print(f'Root Mean Squared Error: {rmse:.2f}')
print(f'R-squared Score: {r2:.2f}')

Mean Absolute Error: 6.07
Mean Squared Error: 80.36
Mean Absolute Percetage Error: 10.74%
Root Mean Squared Error: 8.96
R-squared Score: 0.82

**2. Decision Tree Regressor**

In [18]:
# train model with linear regression
from sklearn.tree import DecisionTreeRegressor

# create pipeline for decision tree
pipeline_dt = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', DecisionTreeRegressor(random_state=42))
])

# train the model with decision tree pipeline
pipeline_dt.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('regressor', DecisionTreeRegressor(random_state=42))])

In [19]:
# predict the test set data
y_pred_dt = pipeline_dt.predict(X_test)

In [20]:
# evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
mape_dt = mean_absolute_percentage_error(y_test, y_pred_dt) * 100
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)


print(f'Mean Absolute Error: {mae_dt:.2f}')
print(f'Mean Squared Error: {mse_dt:.2f}')
print(f'Mean Absolute Percentage Error: {mape_dt:.2f}%')
print(f'Root Mean Squared Error: {rmse_dt:.2f}')
print(f'R-squared Score: {r2_dt:.2f}')

Mean Absolute Error: 11.33
Mean Squared Error: 271.54
Mean Absolute Percentage Error: 21.43%
Root Mean Squared Error: 16.48
R-squared Score: 0.39

**3. Random Forest Regressor**

In [21]:
# import the random forest regressor
from sklearn.ensemble import RandomForestRegressor

# create pipeline for random forest regressor
pipeline_rf = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', RandomForestRegressor(random_state=42))
])

# train the model with random forest regressor pipeline
pipeline_rf.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [22]:
# predict the test set data
y_pred_rf = pipeline_rf.predict(X_test)

In [23]:
# evaluate the model

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
mape_rf = mean_absolute_percentage_error(y_test, y_pred_rf)*100
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f'Mean Absolute Error: {mae_rf:.2f}')
print(f'Mean Squared Error: {mse_rf:.2f}')
print(f'Mean Absolute Percentage Error: {mape_rf:.2f}%')
print(f'Root Mean Squared Error: {rmse_rf:.2f}')
print(f'R-squared Score: {r2_rf:.2f}')

Mean Absolute Error: 6.88
Mean Squared Error: 92.76
Mean Absolute Percentage Error: 12.64%
Root Mean Squared Error: 9.63
R-squared Score: 0.79

**4. XGBoost Regressor**

In [24]:
# import xgboost regressor
from xgboost import XGBRegressor

# create pipeline for xgboost regressor 
pipeline_xgb = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', XGBRegressor(random_state=42))
])

# train the model with xgboost regressor pipeline
pipeline_xgb.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'M...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [25]:
# predict the test set
y_pred_xgb = pipeline_xgb.predict(X_test)

In [26]:
# evaluate the model
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
mape_xgb = mean_absolute_percentage_error(y_test, y_pred_xgb)*100
rmse_xgb = np.sqrt(mse_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)


print(f'Mean Absolute Error: {mae_xgb:.2f}')
print(f'Mean Squared Error: {mse_xgb:.2f}')
print(f'Mean Absolute Percentage Error: {mape_xgb:.2f}%')
print(f'Root Mean Squared Error: {rmse_xgb:.2f}')
print(f'R² Score: {r2_xgb:.2f}')

Mean Absolute Error: 8.18
Mean Squared Error: 128.44
Mean Absolute Percentage Error: 14.71%
Root Mean Squared Error: 11.33
R² Score: 0.71

**5. Ridge Regression**

In [27]:
# import ridge regression
from sklearn.linear_model import Ridge

# create a pipeline for ridge regression
pipeline_ridge = Pipeline([
    ("preprocessing", preprocessor),
    ("model", Ridge(alpha=1.0))
])

# train the model with the training data
pipeline_ridge.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('model', Ridge())])

In [28]:
# predict the test set
y_pred_ridge = pipeline_ridge.predict(X_test)

In [29]:
# evaluate the model

mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
mape_ridge = mean_absolute_percentage_error(y_test, y_pred_ridge)*100
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)


print(f'Mean Absolute Error: {mae_ridge:.2f}')
print(f'Mean Squared Error: {mse_ridge:.2f}')
print(f'Mean Absolute Percentage Error: {mape_ridge:.2f}%')
print(f'Root Mean Squared Error: {rmse_ridge:.2f}')
print(f'R² Score: {r2_ridge:.2f}')

Mean Absolute Error: 6.07
Mean Squared Error: 80.37
Mean Absolute Percentage Error: 10.76%
Root Mean Squared Error: 8.96
R² Score: 0.82

**6. Lasso Regression**

In [30]:
# import library for lasso regression
from sklearn.linear_model import Lasso

# create a pipeline for lasso regression
pipeline_lasso = Pipeline([
    ("preprocessing", preprocessor),
    ("model", Lasso(alpha=1.0))
])

# train the model with the training data
pipeline_lasso.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('model', Lasso())])

In [31]:
# predict the test set
y_pred_lasso = pipeline_lasso.predict(X_test)

In [32]:
# evaluate the model

mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
mape_lasso = mean_absolute_percentage_error(y_test, y_pred_lasso)*100
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print(f'Mean Absolute Error: {mae_lasso:.2f}')
print(f'Mean Squared Error: {mse_lasso:.2f}')
print(f'Mean Absolute Percentage Error: {mape_lasso:.2f}%')
print(f'Root Mean Squared Error: {rmse_lasso:.2f}')
print(f'R² Score: {r2_lasso:.2f}')

Mean Absolute Error: 7.01
Mean Squared Error: 96.54
Mean Absolute Percentage Error: 13.91%
Root Mean Squared Error: 9.83
R² Score: 0.78

**7. Support Vector Regression**

In [33]:
# import library for support vector regression
from sklearn.svm import SVR

# create support vector regression model with radial basis function kernel
pipeline_svr = Pipeline([
    ("preprocessing", preprocessor),
    ("model", SVR(kernel="rbf"))
])

# train the model
pipeline_svr.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Distance_km',
                                                   'Preparation_Time_min',
                                                   'Courier_Experience_yrs']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ordinal',
                                                                   OrdinalEncoder(categories=[['Low',
                                                                                               'Medium',
                                                                                               'High']]))]),
                                                  ['Traffic_Level']),
                                                 ('nom',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Weather', 'Time_of_Day',
                                                   'Vehicle_Type'])])),
                ('model', SVR())])

In [34]:
# predict the test set
y_pred_svr = pipeline_svr.predict(X_test)

In [35]:
# evaluate the model

mae_svr = mean_absolute_error(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
mape_svr = mean_absolute_percentage_error(y_test, y_pred_svr) * 100
rmse_svr = np.sqrt(mse_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f'Mean Absolute Error: {mae_svr:.2f}')
print(f'Mean Squared Error: {mse_svr:.2f}')
print(f'Mean Absolute Percentage Error: {mape_svr:.2f}%')
print(f'Root Mean Squared Error: {rmse_svr:.2f}')
print(f'R² Score: {r2_svr:.2f}')

Mean Absolute Error: 7.09
Mean Squared Error: 105.71
Mean Absolute Percentage Error: 13.67%
Root Mean Squared Error: 10.28
R² Score: 0.76

**Inisght**

Hasil latihan beberapa model menunjukkan bahwa model linear seperti Linear Regression dan Ridge Regression memberikan performa terbaik dengan R² sebesar 0.82 dan MAE sekitar 6 menit. Hal ini mengindikasikan bahwa hubungan antara fitur seperti jarak, waktu persiapan, dan kondisi lalu lintas dengan waktu pengiriman bersifat relatif linear. Model yang lebih kompleks seperti Random Forest dan XGBoost tidak memberikan peningkatan performa yang signifikan, sehingga tidak diperlukan kompleksitas tambahan dalam kasus ini.

# **Cross Validation**

In [36]:
# import libraries
from sklearn.model_selection import cross_val_score

**Linear Regression**

In [37]:
# cross validation for linear regression
cv_scores_lr = cross_val_score(pipeline_linreg, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_scores_lr.round(2))
print(f'Average Cross-validation R2 score: {cv_scores_lr.mean():.2f}')

Cross-validation R2 scores: [0.7  0.81 0.79 0.76 0.78]
Average Cross-validation R2 score: 0.77

**Decision Tree**

In [38]:
# cross validation for decision tree 
cv_scores_dt = cross_val_score(pipeline_dt, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_scores_dt.round(2))
print(f'Average Cross-validation R2 score: {cv_scores_dt.mean():.2f}')

Cross-validation R2 scores: [0.51 0.51 0.34 0.29 0.28]
Average Cross-validation R2 score: 0.38

**Random Forest**

In [39]:
# cross validation for random forest regressor
cv_scores_rf = cross_val_score(pipeline_rf, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_scores_rf.round(2))
print(f'Average Cross-validation R2 score: {cv_scores_rf.mean():.2f}')

Cross-validation R2 scores: [0.65 0.75 0.76 0.71 0.74]
Average Cross-validation R2 score: 0.72

**XGboost**

In [40]:
cv_scores_xgb = cross_val_score(pipeline_xgb, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_scores_xgb.round(2))
print(f'Average Cross-validation R2 score: {cv_scores_xgb.mean():.2f}')

Cross-validation R2 scores: [0.61 0.72 0.73 0.7  0.69]
Average Cross-validation R2 score: 0.69

**Ridge Regression**

In [41]:
cv_score_ridge = cross_val_score(pipeline_ridge, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_score_ridge.round(2))
print(f'Average Cross-validation R2 score: {cv_score_ridge.mean():.2f}')

Cross-validation R2 scores: [0.7  0.81 0.79 0.76 0.78]
Average Cross-validation R2 score: 0.77

**Lasso Regression**

In [42]:
cv_score_lasso = cross_val_score(pipeline_lasso, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_score_lasso.round(2))
print(f'Average Cross-validation R2 score: {cv_score_lasso.mean():.2f}')

Cross-validation R2 scores: [0.66 0.79 0.77 0.74 0.78]
Average Cross-validation R2 score: 0.75

**Support Vector regression**

In [43]:
cv_score_svr = cross_val_score(pipeline_svr, X, y, cv=5, scoring='r2')

print("Cross-validation R2 scores:", cv_score_svr.round(2))
print(f'Average Cross-validation R2 score: {cv_score_svr.mean():.2f}')

Cross-validation R2 scores: [0.65 0.72 0.71 0.68 0.72]
Average Cross-validation R2 score: 0.70

**Insight**

- Model linear menunjukkan performa terbaik dan paling stabil, mengindikasikan bahwa hubungan antar variabel dalam dataset bersifat linear.

- Model kompleks seperti Random Forest dan XGBoost tidak memberikan peningkatan signifikan, sehingga kompleksitas tambahan tidak diperlukan.

- Decision Tree menunjukkan variansi tinggi antar fold, yang mengindikasikan kecenderungan overfitting dan kurangnya kemampuan generalisasi.

- Perbedaan antara hasil single split dan cross-validation menunjukkan pentingnya validasi model untuk mendapatkan estimasi performa yang lebih realistis.

# **Tuning The Best Model**

**Linear regression is the best model**

In [44]:
# import library grid search cv
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

In [45]:
# create ridge regression model
ridge = Ridge()

pipeline_ridge = Pipeline([
    ("preprocessing", preprocessor),
    ("model", ridge)
])

# set parameter grid for alpha
param_grid = {
    'model__alpha': [0.001, 0.01, 0.1, 1, 10, 100, 1000]
}

# create grid search cv
grid = GridSearchCV(
    pipeline_ridge,
    param_grid,
    cv=5,
    scoring='r2'
)

# train the model with grid search cv
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['Distance_km',
                                                                          'Preparation_Time_min',
                                                                          'Courier_Experience_yrs']),
                                                                        ('ord',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('ordinal',
                                                                                          OrdinalEncoder(categories=[['Low',
                                                                                                                      'Medium',
                                                                                                                      'High']]))]),
                                                                         ['Traffic_Level']),
                                                                        ('nom',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehot',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['Weather',
                                                                          'Time_of_Day',
                                                                          'Vehicle_Type'])])),
                                       ('model', Ridge())]),
             param_grid={'model__alpha': [0.001, 0.01, 0.1, 1, 10, 100, 1000]},
             scoring='r2')

In [46]:
# Show best alpha
print(grid.best_params_)

# show the best score
print(grid.best_score_.round(2))

{'model__alpha': 10}
0.75

the best model alpha for ridge regression is **10**

In [47]:
# best model
best_model = grid.best_estimator_

In [48]:
# predict the test set with best model
y_pred_best_model = best_model.predict(X_test)

In [49]:
# Evaluate the model after tuning

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_grid = mean_absolute_error(y_test, y_pred_best_model)
mse_grid= mean_squared_error(y_test, y_pred_best_model)
mape_grid = mean_absolute_percentage_error(y_test, y_pred_best_model)*100
rmse_grid= np.sqrt(mse_grid)
r2_grid= r2_score(y_test, y_pred_best_model)

print(f'Mean Absolute Error: {mae_grid:.2f}')
print(f'Mean Squared Error: {mse_grid:.2f}')
print(f'Mean Absolute Percentage Error: {mape_grid:.2f}%')
print(f'Root Mean Squared Error: {rmse_grid:.2f}')
print(f'R² Score: {r2_grid:.2f}')

Mean Absolute Error: 6.11
Mean Squared Error: 80.57
Mean Absolute Percentage Error: 10.96%
Root Mean Squared Error: 8.98
R² Score: 0.82

In [51]:
# import library
import joblib

# save the best model to a file
joblib.dump(best_model, 'model_delivery_time_prediction.pkl')

['model_delivery_time_prediction.pkl']